package sic.modelo;

public enum TipoDeComprobante {
  FACTURA_A,
  FACTURA_B,
  FACTURA_C,
  FACTURA_X,
  FACTURA_Y,
  PEDIDO,
  PRESUPUESTO,
  RECIBO,
  GASTO,
  NOTA_CREDITO_A,
  NOTA_CREDITO_B,
  NOTA_CREDITO_X,
  NOTA_CREDITO_Y,
  NOTA_CREDITO_PRESUPUESTO,
  NOTA_DEBITO_A,
  NOTA_DEBITO_B,
  NOTA_DEBITO_X,
  NOTA_DEBITO_Y,
  NOTA_DEBITO_PRESUPUESTO
}
